version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - 8080:8080
      - 9299:9229 # enable debugging
    expose:
      - '8080'
    volumes:
      - .:/usr/src/app
      - ./usr/src/app/node_modules
    command: npm run dev
    environment:
      PORT: 8080